const happinessAffirmations = [
    "I am deserving of happiness and joy.",
    "Happiness is my birthright, and I claim it now.",
    "I choose to focus on the positive aspects of my life.",
    "I am grateful for the simple pleasures that bring me joy.",
    "I radiate happiness and attract positive vibes into my life.",
    "I find joy in every moment and celebrate the gift of life.",
    "My life is filled with love, joy, and abundance.",
    "I am in control of my happiness, and I choose to be happy now.",
    "I let go of worries and embrace a sense of peace and happiness.",
    "I am the architect of my own happiness, and I build it daily.",
    "I choose happiness over fear, doubt, and negativity.",
    "Happiness flows into my life effortlessly and abundantly.",
    "I am surrounded by positive energy and happy people.",
    "I am a magnet for joyful experiences and positive outcomes.",
    "I am grateful for the happiness that is present in my life.",
    "I release any resistance to happiness and allow it to flow freely.",
    "I am worthy of all the joy and happiness life has to offer.",
    "I am a beacon of happiness, and it spreads to those around me.",
    "I choose activities and people that bring joy into my life.",
    "I am the master of my thoughts, and I choose happiness.",
    "Every day, in every way, I am getting happier and happier.",
    "Happiness is my natural state of being.",
    "I am at peace with my past, present, and future, and I am happy.",
    "I am grateful for the abundance of happiness in my life.",
    "I release the need to compare myself to others and find joy in being me.",
    "I attract positive and uplifting experiences that bring me joy.",
    "My heart is open to love, kindness, and happiness.",
    "I am surrounded by the beauty and joy of the present moment.",
    "I am grateful for the lessons that bring me closer to happiness.",
    "I choose thoughts that make me feel good and lead to happiness.",
    "I am a source of happiness and positivity for others.",
    "I release any attachment to unhappiness and embrace joy.",
    "I am open to receiving all the happiness and abundance life has to offer.",
    "Happiness is a choice, and I choose to be happy now.",
    "I am grateful for the happiness that is unfolding in my life.",
    "I find joy in the journey and express gratitude for my experiences.",
    "I am a reservoir of happiness, and it overflows into my life.",
    "I am worthy of happiness, and I allow it to flow into every area of my life.",
    "I let go of anything that robs me of my happiness and peace of mind.",
    "I attract joyous experiences, and my life is a reflection of my positive mindset.",
    "I am in tune with the energy of happiness, and it surrounds me.",
    "I am a magnet for happiness, and it gravitates toward me.",
    "I choose to let go of negative thoughts and embrace a state of happiness.",
    "Happiness resides within me, and I carry it with me wherever I go.",
    "I am grateful for the abundant happiness that fills my life.",
    "I release the need for perfection and embrace the joy of being imperfectly me.",
    "I am open to the abundance of joy and happiness that the universe offers.",
    "I am a beacon of happiness, and I share my joy with the world.",
    "My life is a reflection of the joy and positivity that I cultivate within."
]

export { happinessAffirmations }


 