const iAmAffirmations = [
    "I am worthy of love and kindness.",
    "I choose joy and abundance in my life.",
    "I believe in my abilities and potential.",
    "I am confident in the person I am becoming.",
    "I am resilient, and I can overcome any challenge.",
    "My thoughts create my reality, and I focus on positivity.",
    "I attract positivity and repel negativity.",
    "I am deserving of success and happiness.",
    "I trust in my journey and embrace the process of growth.",
    "I am grateful for the abundance in my life.",
    "I am a beacon of love and compassion.",
    "I forgive myself and release all feelings of guilt.",
    "I am surrounded by supportive and uplifting people.",
    "I radiate confidence, self-respect, and inner harmony.",
    "I am in control of my thoughts, and I choose positivity.",
    "I am open to new opportunities and adventures.",
    "I am a magnet for miracles.",
    "I am worthy of achieving my goals and dreams.",
    "I choose to let go of what I cannot control.",
    "I am at peace with my past and excited for my future.",
    "I trust the journey, even when I do not understand it.",
    "I am constantly evolving and improving.",
    "I am a source of inspiration for others.",
    "I am a powerful creator of my own reality.",
    "I am deserving of all the good things life has to offer.",
    "I release all doubts and embrace my inner strength.",
    "I am resilient, strong, and capable.",
    "I attract positive and uplifting experiences.",
    "I am proud of myself and my accomplishments.",
    "I choose to focus on what I can control and let go of the rest.",
    "I am a unique and valuable person.",
    "I am surrounded by love and positive energy.",
    "I am a magnet for success and prosperity.",
    "I trust the process of life and let go of the need for control.",
    "I am deserving of love, respect, and happiness.",
    "I am confident in my abilities to achieve my goals.",
    "I am at peace with who I am.",
    "I am a beacon of light and positivity.",
    "I choose to see the good in myself and others.",
    "I am constantly learning and growing.",
    "I radiate confidence, self-respect, and inner harmony.",
    "I am capable of handling whatever comes my way.",
    "I am surrounded by love, and my heart is open to receive it.",
    "I am a source of love and inspiration.",
    "I am resilient, and I bounce back from challenges with ease.",
    "I trust that everything is unfolding for my highest good.",
    "I am worthy of success, happiness, and fulfillment.",
    "I am grateful for the opportunities life presents to me.",
    "I am a magnet for positive relationships and connections.",
    "I am in control of my thoughts, and I choose positivity."
  ];

  export { iAmAffirmations }