const loveAndRelationshipsAffirmations  = [
    "I am worthy of love and connection.",
    "I attract healthy and fulfilling relationships.",
    "I am open to giving and receiving love.",
    "My heart is open to new and positive experiences in relationships.",
    "I choose to forgive and let go of past hurts in my relationships.",
    "I communicate with love and respect in my relationships.",
    "I am deserving of a loving and supportive partner.",
    "I trust the journey of my relationships and the lessons they bring.",
    "I am grateful for the love and joy that my relationships bring into my life.",
    "I am a magnet for positive and loving people.",
    "I create space for healthy and harmonious connections in my life.",
    "I am committed to the growth and well-being of my relationships.",
    "I release any fear or doubt that may hinder my relationships.",
    "I choose to see the best in myself and others in my relationships.",
    "I am capable of creating and maintaining fulfilling connections.",
    "I attract love by being myself and embracing my authenticity.",
    "I am a source of love and positivity in my relationships.",
    "I let go of any toxic relationships that no longer serve me.",
    "I am deserving of unconditional love and acceptance.",
    "I trust in the divine timing of my relationships.",
    "I am grateful for the lessons and growth that come from my relationships.",
    "I am open to giving and receiving love in abundance.",
    "I radiate love and attract loving energy into my life.",
    "I am surrounded by supportive and uplifting relationships.",
    "I choose partners who enhance my life and share my values.",
    "I am deserving of deep, meaningful, and fulfilling connections.",
    "I let go of any expectations and allow my relationships to unfold naturally.",
    "I am a valuable and lovable person worthy of great relationships.",
    "I attract positive and healthy communication in my relationships.",
    "I am comfortable expressing my needs and desires in my relationships.",
    "I release any attachment to past relationship patterns that no longer serve me.",
    "I am grateful for the unique qualities and perspectives my partner brings.",
    "I am committed to creating a loving and supportive partnership.",
    "I am worthy of experiencing true intimacy and connection.",
    "I trust myself to choose partners who align with my highest good.",
    "I am open to the beautiful possibilities that love brings into my life.",
    "I am a magnet for loving, harmonious, and fulfilling relationships.",
    "I am deserving of happiness and love in all aspects of my life.",
    "I attract partners who appreciate and cherish me for who I am.",
    "I let go of any fear of vulnerability in my relationships.",
    "I am deserving of a love that is pure, passionate, and authentic.",
    "I am open to creating deep emotional connections in my relationships.",
    "I choose love over fear in all of my relationships.",
    "I am grateful for the love that flows effortlessly into my life.",
    "I trust that every relationship experience is a valuable part of my journey.",
    "I am surrounded by love, and I attract loving relationships effortlessly.",
    "I am a magnet for positive and respectful communication in my relationships.",
    "I am worthy of experiencing love in its highest form.",
    "I release any resistance to love and embrace it fully in my life.",
    "I am open to giving and receiving love without fear or judgment.",
    "I am a loving and lovable partner, and I attract the same energy in return."
]

export { loveAndRelationshipsAffirmations }