const stoicAffirmations = [
    "It's not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control. \n - Epictetus",
    "It is not the man who has too little, but the man who craves more, that is poor. \n - Seneca",
    "The best revenge is to be unlike him who performed the injustice. \n - Marcus Aurelius",
    "He who fears death will never do anything worth of a man who is alive. \n - Seneca",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "He who is brave is free. \n - Seneca",
    "Waste no more time arguing about what a good man should be. Be one. \n - Marcus Aurelius",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "He suffers more than necessary, who suffers before it is necessary. \n - Seneca",
    "The best revenge is to be unlike him who performed the injustice. \n - Marcus Aurelius",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "He who fears death will never do anything worth of a man who is alive. \n - Seneca",
    "It is not that we have a short time to live, but that we waste much of it. - Seneca",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "He who is brave is free. \n - Seneca",
    "Waste no more time arguing about what a good man should be. Be one. \n - Marcus Aurelius",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "He suffers more than necessary, who suffers before it is necessary. \n - Seneca",
    "The best revenge is to be unlike him who performed the injustice. \n - Marcus Aurelius",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "He who fears death will never do anything worth of a man who is alive. \n - Seneca",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "He who is brave is free. \n - Seneca",
    "Waste no more time arguing about what a good man should be. Be one. \n - Marcus Aurelius",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "He suffers more than necessary, who suffers before it is necessary. \n - Seneca",
    "The best revenge is to be unlike him who performed the injustice. \n - Marcus Aurelius",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "He who fears death will never do anything worth of a man who is alive. \n - Seneca",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "He who is brave is free. \n - Seneca",
    "Waste no more time arguing about what a good man should be. Be one. \n - Marcus Aurelius",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "He suffers more than necessary, who suffers before it is necessary. \n - Seneca",
    "The best revenge is to be unlike him who performed the injustice. \n - Marcus Aurelius",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "He who fears death will never do anything worth of a man who is alive. \n - Seneca",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "He who is brave is free. \n - Seneca",
    "Waste no more time arguing about what a good man should be. Be one. \n - Marcus Aurelius",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "He suffers more than necessary, who suffers before it is necessary. \n - Seneca",
    "The best revenge is to be unlike him who performed the injustice. \n - Marcus Aurelius",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "He who fears death will never do anything worth of a man who is alive. \n - Seneca",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "He who is brave is free. \n - Seneca",
    "Waste no more time arguing about what a good man should be. Be one. \n - Marcus Aurelius",
    "It is not that we have a short time to live, but that we waste much of it. \n - Seneca",
    "He suffers more than necessary, who suffers before it is necessary. \n - Seneca"
  ];

  export { stoicAffirmations }