const zenAffirmations = [
    "The quieter you become, the more you can hear. - Zen proverb",
    "Do not seek the truth; only cease to cherish opinions. - Seng-ts'an",
    "The one who is good at shooting does not hit the center of the target. - Zen proverb",
    "Empty your mind, be formless, shapeless, like water. - Bruce Lee",
    "Before enlightenment, chop wood, carry water. After enlightenment, chop wood, carry water. - Zen proverb",
    "When you get to the top of the mountain, keep climbing. - Zen proverb",
    "The obstacle is the path. - Zen proverb",
    "Let go or be dragged. - Zen proverb",
    "To follow the path, look to the master, follow the master, walk with the master, see through the master, become the master. - Zen proverb",
    "Nothing ever exists entirely alone. Everything is in relation to everything else. - Buddha",
    "If you want to know your past, look into your present conditions. If you want to know your future, look into your present actions. - Zen proverb",
    "Sitting quietly, doing nothing, spring comes, and the grass grows by itself. - Zen proverb",
    "In the beginner's mind, there are many possibilities; in the expert's mind, there are few. - Shunryu Suzuki",
    "You should sit in meditation for twenty minutes every day, unless you're too busy. Then you should sit for an hour. - Zen proverb",
    "The more you know, the less you understand. - Lao Tzu",
    "A flower falls, even though we love it, and a weed grows, even though we do not love it. - Dogen Zenji",
    "To understand everything is to forgive everything. - Zen proverb",
    "A jug fills drop by drop. - Buddha",
    "The best way out is always through. - Robert Frost",
    "The moon has no intention of casting its reflection on the water, nor does the water have any intention of reflecting the moon; the reflection naturally appears when the water is still. - Dogen Zenji",
    "Don't seek, don't search, don't ask, don't knock, don't demand – relax. If you relax, it comes. If you relax, it is there. If you relax, you start vibrating with it. - Osho",
    "Life is a journey that must be traveled no matter how bad the roads and accommodations. - Oliver Goldsmith",
    "To follow the path, look to the master, follow the master, walk with the master, see through the master, become the master. - Zen proverb",
    "Not thinking about anything is Zen. Once you know this, walking, sitting, or lying down, everything you do is Zen. - Bodhidharma",
    "Zen is not some kind of excitement, but concentration on our usual everyday routine. - Shunryu Suzuki",
    "Zen is not to be found in the scriptures. - Bodhidharma",
    "A Zen master's life is one continuous mistake. - Dogen Zenji",
    "The great way is not difficult if you just don't pick and choose. - Seng-ts'an",
    "The mind of the beginner is empty, free of the habits of the expert, ready to accept, to doubt, and open to all the possibilities. - Shunryu Suzuki",
    "A flower falls, even though we love it, and a weed grows, even though we do not love it. - Dogen Zenji",
    "When you realize nothing is lacking, the whole world belongs to you. - Lao Tzu",
    "The present moment is filled with joy and happiness. If you are attentive, you will see it. - Thich Nhat Hanh",
    "The best way to control people is to encourage them to be mischievous. Then they will be in control in its wider sense. To give your sheep or cow a large spacious meadow is the way to control him. So it is with people: first let them do what they want, and watch them. This is the best policy. To ignore them is not good. That is the worst policy. The second worst is trying to control them. The best one is to watch them, just to watch them, without trying to control them. - Shunryu Suzuki",
    "When you can do nothing, what can you do? - Zen proverb",
    "Before enlightenment, I chopped wood and carried water. After enlightenment, I chopped wood and carried water. - Zen proverb",
    "The moon has no intention of casting its reflection on the water, nor does the water have any intention of reflecting the moon; the reflection naturally appears when the water is still. - Dogen Zenji",
    "The mind is everything. What you think you become. - Buddha",
    "Nothing ever exists entirely alone. Everything is in relation to everything else. - Buddha",
    "To know and not to do is not to know. - Zen proverb",
    "Be master of mind rather than mastered by mind. - Zen proverb",
    "If you want to fly, give up everything that weighs you down. - Buddha",
    "To follow the path, look to the master, follow the master, walk with the master, see through the master, become the master. - Zen proverb",
    "When you get free from views and words, reality reveals itself to you, and that is Nirvana. - Thich Nhat Hanh",
    "Be where you are; otherwise, you will miss your life. - Buddha",
    "The obstacle is the path. - Zen proverb",
    "In the beginner's mind, there are many possibilities; in the expert's mind, there are few. - Shunryu Suzuki",
    "The quieter you become, the more you can hear. - Ram Dass",
    "Sitting quietly, doing nothing, spring comes, and the grass grows by itself. - Zen proverb",
    "The best way to control people is to encourage them to be mischievous. Then they will be in control in its wider sense. To give your sheep or cow a large spacious meadow is the way to control him. So it is with people: first let them do what they want, and watch them. This is the best policy. To ignore them is not good. That is the worst policy. The second worst is trying to control them. The best one is to watch them, just to watch them, without trying to control them. - Shunryu Suzuki"
]

export { zenAffirmations }